import type { Agent, Property } from "./types";

export const agents: Agent[] = [
  {
    id: "daniel-morgan",
    name: "Daniel Morgan",
    role: "Managing Director",
    photo: "/images/team-01.jpg",
    email: "daniel@horizonproperties.com",
    phone: "(555) 246-7890",
    bio: "Daniel founded Horizon Properties after eighteen years advising private clients on architectural and waterfront homes. He leads the firm's advisory practice and negotiates its most significant transactions.",
  },
  {
    id: "olivia-carter",
    name: "Olivia Carter",
    role: "Luxury Property Advisor",
    photo: "/images/team-02.jpg",
    email: "olivia@horizonproperties.com",
    phone: "(555) 246-7891",
    bio: "Olivia represents buyers and sellers across the West Coast, with a particular focus on contemporary architecture and design-led estates.",
  },
  {
    id: "james-wilson",
    name: "James Wilson",
    role: "Investment Consultant",
    photo: "/images/team-03.jpg",
    email: "james@horizonproperties.com",
    phone: "(555) 246-7892",
    bio: "James builds acquisition strategy for private and institutional investors, grounding every recommendation in rental yield, supply and long-hold value.",
  },
  {
    id: "sophia-bennett",
    name: "Sophia Bennett",
    role: "Senior Property Specialist",
    photo: "/images/team-04.jpg",
    email: "sophia@horizonproperties.com",
    phone: "(555) 246-7893",
    bio: "Sophia guides relocation and first-home clients through every stage of the process, from shortlist to settlement, with a reputation for calm precision.",
  },
];

const galleries: Record<string, string[]> = {
  ext01: ["/images/ext-01.jpg", "/images/int-01.jpg", "/images/int-02.jpg", "/images/ext-11.jpg", "/images/int-03.jpg"],
  ext02: ["/images/ext-02.jpg", "/images/int-02.jpg", "/images/ext-12.jpg", "/images/int-04.jpg", "/images/int-05.jpg"],
  ext03: ["/images/ext-03.jpg", "/images/int-03.jpg", "/images/int-06.jpg", "/images/ext-09.jpg", "/images/int-01.jpg"],
  ext04: ["/images/ext-04.jpg", "/images/int-04.jpg", "/images/ext-13.jpg", "/images/int-02.jpg", "/images/int-06.jpg"],
  ext05: ["/images/ext-05.jpg", "/images/int-05.jpg", "/images/ext-07.jpg", "/images/int-03.jpg", "/images/int-01.jpg"],
  ext06: ["/images/ext-06.jpg", "/images/int-06.jpg", "/images/ext-10.jpg", "/images/int-04.jpg", "/images/int-02.jpg"],
  ext07: ["/images/ext-07.jpg", "/images/int-01.jpg", "/images/ext-13.jpg", "/images/int-05.jpg", "/images/int-03.jpg"],
  ext08: ["/images/ext-08.jpg", "/images/int-03.jpg", "/images/ext-11.jpg", "/images/int-06.jpg", "/images/int-04.jpg"],
  ext09: ["/images/ext-09.jpg", "/images/int-02.jpg", "/images/ext-05.jpg", "/images/int-01.jpg", "/images/int-05.jpg"],
  ext10: ["/images/ext-10.jpg", "/images/int-05.jpg", "/images/ext-12.jpg", "/images/int-03.jpg", "/images/int-06.jpg"],
  ext11: ["/images/ext-11.jpg", "/images/int-04.jpg", "/images/ext-01.jpg", "/images/int-02.jpg", "/images/int-05.jpg"],
  ext12: ["/images/ext-12.jpg", "/images/int-06.jpg", "/images/ext-06.jpg", "/images/int-01.jpg", "/images/int-03.jpg"],
};

const baseFeatures = [
  "Floor-to-ceiling glazing",
  "Chef's kitchen with integrated appliances",
  "Primary suite with dressing room",
  "Home office / study",
  "Smart home automation",
];

const baseAmenities = [
  "Infinity pool",
  "Landscaped grounds",
  "Covered outdoor lounge",
  "Wine cellar",
  "Three-car garage",
  "Guest house",
];

export const properties: Property[] = [
  {
    id: "p1",
    slug: "lakeside-modern-villa",
    name: "Lakeside Modern Villa",
    location: "Austin, Texas, USA",
    city: "Austin",
    state: "Texas",
    price: 2_350_000,
    type: "Villa",
    beds: 5,
    baths: 5,
    sqft: 6_200,
    year: 2021,
    featured: true,
    image: "/images/ext-01.jpg",
    gallery: galleries.ext01,
    description:
      "A restrained, light-filled villa set on a private stretch of the lake. Concrete, oak and glass are held in balance across two levels, with a double-height living room opening directly onto the water terrace.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "daniel-morgan",
  },
  {
    id: "p2",
    slug: "pacific-glass-house",
    name: "Pacific Glass House",
    location: "Malibu, California, USA",
    city: "Malibu",
    state: "California",
    price: 4_800_000,
    type: "House",
    beds: 6,
    baths: 6,
    sqft: 7_400,
    year: 2019,
    featured: true,
    image: "/images/ext-02.jpg",
    gallery: galleries.ext02,
    description:
      "Perched above the coastline, this glass pavilion is designed around the horizon. Sliding walls dissolve the boundary between living space and the terrace, pool and uninterrupted ocean view beyond.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "olivia-carter",
  },
  {
    id: "p3",
    slug: "desert-horizon-estate",
    name: "Desert Horizon Estate",
    location: "Scottsdale, Arizona, USA",
    city: "Scottsdale",
    state: "Arizona",
    price: 3_150_000,
    type: "Estate",
    beds: 5,
    baths: 4,
    sqft: 5_800,
    year: 2022,
    featured: true,
    image: "/images/ext-03.jpg",
    gallery: galleries.ext03,
    description:
      "Low-slung and quietly monumental, this estate frames the desert through deep reveals and shaded courtyards. Warm stone, bronze and timber respond to the light through the day.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "james-wilson",
  },
  {
    id: "p4",
    slug: "oceanfront-residence",
    name: "Oceanfront Residence",
    location: "Miami, Florida, USA",
    city: "Miami",
    state: "Florida",
    price: 5_200_000,
    type: "Residence",
    beds: 6,
    baths: 7,
    sqft: 8_100,
    year: 2020,
    featured: true,
    image: "/images/ext-04.jpg",
    gallery: galleries.ext04,
    description:
      "Direct ocean frontage, a private dock and a sequence of terraces that follow the sun. The residence is engineered for entertaining while keeping the family quarters entirely separate.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "sophia-bennett",
  },
  {
    id: "p5",
    slug: "modern-hillside-retreat",
    name: "Modern Hillside Retreat",
    location: "Los Angeles, California, USA",
    city: "Los Angeles",
    state: "California",
    price: 3_750_000,
    type: "Retreat",
    beds: 4,
    baths: 4,
    sqft: 5_100,
    year: 2018,
    featured: true,
    image: "/images/ext-05.jpg",
    gallery: galleries.ext05,
    description:
      "Cantilevered over the canyon, the retreat opens to city views on one side and stillness on the other. Interiors are warm and pared back, with a lap pool running the length of the terrace.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "olivia-carter",
  },
  {
    id: "p6",
    slug: "palm-garden-residence",
    name: "Palm Garden Residence",
    location: "Beverly Hills, California, USA",
    city: "Beverly Hills",
    state: "California",
    price: 6_400_000,
    type: "Estate",
    beds: 7,
    baths: 8,
    sqft: 9_300,
    year: 2023,
    featured: true,
    image: "/images/ext-06.jpg",
    gallery: galleries.ext06,
    description:
      "A mature garden estate behind private gates, restored and extended with a light touch. Formal lawns, a guest house and a long pool terrace give the house a rare sense of scale.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "daniel-morgan",
  },
  {
    id: "p7",
    slug: "contemporary-lake-house",
    name: "Contemporary Lake House",
    location: "Lake Tahoe, Nevada, USA",
    city: "Lake Tahoe",
    state: "Nevada",
    price: 2_950_000,
    type: "House",
    beds: 4,
    baths: 4,
    sqft: 4_800,
    year: 2021,
    featured: true,
    image: "/images/ext-07.jpg",
    gallery: galleries.ext07,
    description:
      "Timber, stone and glass in a quiet composition on the water's edge. A boathouse, sauna and bunk room make the house as practical in winter as it is in summer.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "james-wilson",
  },
  {
    id: "p8",
    slug: "architectural-downtown-penthouse",
    name: "Architectural Downtown Penthouse",
    location: "Austin, Texas, USA",
    city: "Austin",
    state: "Texas",
    price: 1_850_000,
    type: "Penthouse",
    beds: 3,
    baths: 3,
    sqft: 3_200,
    year: 2022,
    featured: true,
    image: "/images/ext-08.jpg",
    gallery: galleries.ext08,
    description:
      "The upper floor of a landmark tower, wrapped in glass with a private roof garden. A rare combination of downtown walkability and genuine outdoor space.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "sophia-bennett",
  },
  {
    id: "p9",
    slug: "cliffside-glass-pavilion",
    name: "Cliffside Glass Pavilion",
    location: "Big Sur, California, USA",
    city: "Big Sur",
    state: "California",
    price: 7_100_000,
    type: "Villa",
    beds: 5,
    baths: 5,
    sqft: 6_700,
    year: 2017,
    featured: false,
    image: "/images/ext-09.jpg",
    gallery: galleries.ext09,
    description:
      "A singular house on a protected bluff, with the Pacific on three sides. Designed for solitude, with every principal room turned toward the water.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "olivia-carter",
  },
  {
    id: "p10",
    slug: "canyon-ridge-villa",
    name: "Canyon Ridge Villa",
    location: "Sedona, Arizona, USA",
    city: "Sedona",
    state: "Arizona",
    price: 2_600_000,
    type: "Villa",
    beds: 4,
    baths: 5,
    sqft: 4_600,
    year: 2020,
    featured: false,
    image: "/images/ext-10.jpg",
    gallery: galleries.ext10,
    description:
      "Set against the red rock, this villa is organised around a shaded central courtyard. Earth-toned materials and deep overhangs keep the interiors cool and calm.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "james-wilson",
  },
  {
    id: "p11",
    slug: "harbor-light-residence",
    name: "Harbor Light Residence",
    location: "Sausalito, California, USA",
    city: "Sausalito",
    state: "California",
    price: 4_150_000,
    type: "Residence",
    beds: 5,
    baths: 5,
    sqft: 5_500,
    year: 2019,
    featured: false,
    image: "/images/ext-11.jpg",
    gallery: galleries.ext11,
    description:
      "A waterfront house with a private berth and wide views across the bay to the city. Interiors are quiet and generous, with a glazed living hall at their centre.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "daniel-morgan",
  },
  {
    id: "p12",
    slug: "sonoma-vineyard-estate",
    name: "Sonoma Vineyard Estate",
    location: "Sonoma, California, USA",
    city: "Sonoma",
    state: "California",
    price: 5_750_000,
    type: "Estate",
    beds: 6,
    baths: 6,
    sqft: 7_900,
    year: 2016,
    featured: false,
    image: "/images/ext-12.jpg",
    gallery: galleries.ext12,
    description:
      "A working vineyard estate with a restored farmhouse, guest cottages and a tasting pavilion. Forty acres of planted vines and a long, private approach.",
    features: baseFeatures,
    amenities: baseAmenities,
    agentId: "sophia-bennett",
  },
];

export const propertyTypes = [
  "Villa",
  "House",
  "Penthouse",
  "Estate",
  "Retreat",
  "Residence",
] as const;

export function getPropertyBySlug(slug: string): Property | undefined {
  return properties.find((p) => p.slug === slug);
}

export function getAgent(id: string): Agent {
  return agents.find((a) => a.id === id) ?? agents[0];
}

export function getSimilarProperties(property: Property, limit = 3): Property[] {
  return properties
    .filter((p) => p.id !== property.id)
    .sort((a, b) => {
      const aScore = (a.type === property.type ? 2 : 0) + (a.state === property.state ? 1 : 0);
      const bScore = (b.type === property.type ? 2 : 0) + (b.state === property.state ? 1 : 0);
      return bScore - aScore;
    })
    .slice(0, limit);
}

export const locations = Array.from(
  new Set(properties.map((p) => p.city))
).sort();

export const priceBounds = {
  min: Math.min(...properties.map((p) => p.price)),
  max: Math.max(...properties.map((p) => p.price)),
};
